### ISSUE TITLE
Create Theme Template

### ISSUE THREAD

**Issue by LUXIANZE** [Five-Fishes/On-Demand-Car-Servicing-App#3]
- [x] Create template for application theme that would be used consistently throughout the project development.
- [x] Ensure the UI controls created are all reusable components to enhance consistency

**Comment by eunicechy** [comment]
so, right now, I had completed the first task or I will need to design the rest of the pages? @LUXIANZE

**Comment by LUXIANZE** [comment]
> so, right now, I had completed the first task or I will need to design the rest of the pages? @LUXIANZE

@eunicechy you have completed the first task, when I have came out with all the pages that we need, verified with dr, then you will need to design the rest of the pages.

**Comment by eunicechy** [comment]
@LUXIANZE for the second task, how you want me to show it in figma?

**Comment by LUXIANZE** [comment]
> @LUXIANZE for the second task, how you want me to show it in figma?

@eunicechy Okay, it is like this. If you noticed, Figma provides a feature to turn a group of stuff into a **component**, you can do that to things that are likely reusable, for example:
- Page background (create a templated frame with background and unchanged parts like dummy page title)
- Buttons (Danger, Success, Info, Warning)
- Other kind of Icon Buttons

Move all these components to **standard components** frame so that other members can reuse easily. Also, as a reminder, do practice **meaningful naming** to components and Frames created and apply **prototyping** in future design (scrollable and clickable)
